/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'remark' : string,
  'customerName' : string,
  'doctorAddress' : string,
  'totalGST' : bigint,
  'grandTotal' : bigint,
  'billDate' : Time,
  'invoiceNumber' : string,
  'customerAddress' : string,
  'billNumber' : bigint,
  'paymentMode' : PaymentMode,
  'customerId' : bigint,
  'items' : Array<BillItem>,
  'doctorName' : string,
  'totalDiscount' : bigint,
  'subtotal' : bigint,
}
export interface BillItem {
  'cgst' : bigint,
  'pack' : string,
  'sgst' : bigint,
  'hsnCode' : string,
  'discountPercent' : bigint,
  'gstAmount' : bigint,
  'quantity' : bigint,
  'batch' : string,
  'expiry' : string,
  'unitPrice' : bigint,
  'medicineId' : bigint,
  'medicineName' : string,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DashboardStats {
  'todayBillCount' : bigint,
  'lowStockMedicinesCount' : bigint,
  'todayTotalSales' : bigint,
  'totalMedicinesInStock' : bigint,
}
export interface Distributor {
  'id' : bigint,
  'drugLicenseNumber' : string,
  'gstNumber' : string,
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Medicine {
  'id' : bigint,
  'manufacturer' : string,
  'purchasePrice' : bigint,
  'expiryDate' : string,
  'name' : string,
  'unit' : Unit,
  'gstPercent' : bigint,
  'sellingPrice' : bigint,
  'rackLocation' : string,
  'hsnCode' : string,
  'batchNumber' : string,
  'genericName' : string,
  'reorderLevel' : bigint,
  'currentStock' : bigint,
}
export type PaymentMode = { 'UPI' : null } |
  { 'card' : null } |
  { 'cash' : null };
export interface PharmacyProfile {
  'drugLicenseNumber' : string,
  'gstNumber' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Purchase {
  'id' : bigint,
  'purchaseDate' : Time,
  'distributorName' : string,
  'distributorId' : bigint,
  'totalGST' : bigint,
  'grandTotal' : bigint,
  'invoiceDate' : string,
  'invoiceNumber' : string,
  'items' : Array<PurchaseItem>,
  'subtotal' : bigint,
}
export interface PurchaseItem {
  'mrp' : bigint,
  'qty' : bigint,
  'purchaseRate' : bigint,
  'pack' : string,
  'gstPercent' : bigint,
  'hsnCode' : string,
  'freeQty' : bigint,
  'batch' : string,
  'expiry' : string,
  'medicineId' : bigint,
  'amount' : bigint,
  'medicineName' : string,
}
export interface PurchaseReturn {
  'id' : bigint,
  'remark' : string,
  'distributorGst' : string,
  'distributorDlNo' : string,
  'distributorName' : string,
  'distributorId' : bigint,
  'totalGST' : bigint,
  'grandTotal' : bigint,
  'distributorAddress' : string,
  'items' : Array<PurchaseReturnItem>,
  'returnNumber' : bigint,
  'returnDate' : Time,
  'subtotal' : bigint,
}
export interface PurchaseReturnItem {
  'cgst' : bigint,
  'pack' : string,
  'sgst' : bigint,
  'hsnCode' : string,
  'gstAmount' : bigint,
  'quantity' : bigint,
  'batch' : string,
  'expiry' : string,
  'unitPrice' : bigint,
  'medicineId' : bigint,
  'amount' : bigint,
  'medicineName' : string,
}
export interface SalesReturn {
  'id' : bigint,
  'remark' : string,
  'customerName' : string,
  'doctorAddress' : string,
  'totalGST' : bigint,
  'grandTotal' : bigint,
  'customerAddress' : string,
  'customerId' : bigint,
  'items' : Array<SalesReturnItem>,
  'doctorName' : string,
  'returnNumber' : bigint,
  'returnDate' : Time,
  'subtotal' : bigint,
}
export interface SalesReturnItem {
  'cgst' : bigint,
  'pack' : string,
  'sgst' : bigint,
  'hsnCode' : string,
  'gstAmount' : bigint,
  'quantity' : bigint,
  'batch' : string,
  'expiry' : string,
  'unitPrice' : bigint,
  'medicineId' : bigint,
  'amount' : bigint,
  'medicineName' : string,
}
export type Time = bigint;
export type Unit = { 'bottle' : null } |
  { 'tablet' : null } |
  { 'strip' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export interface _SERVICE {
  'addCustomer' : ActorMethod<[Customer], bigint>,
  'addDistributor' : ActorMethod<[Distributor], bigint>,
  'addMedicine' : ActorMethod<[Medicine], bigint>,
  'addPurchase' : ActorMethod<[Purchase], bigint>,
  'createBill' : ActorMethod<[Bill], bigint>,
  'createPurchaseReturn' : ActorMethod<[PurchaseReturn], bigint>,
  'createSalesReturn' : ActorMethod<[SalesReturn], bigint>,
  'deleteBill' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteDistributor' : ActorMethod<[bigint], undefined>,
  'deleteMedicine' : ActorMethod<[bigint], undefined>,
  'deletePurchaseReturn' : ActorMethod<[bigint], undefined>,
  'deleteSalesReturn' : ActorMethod<[bigint], undefined>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllDistributors' : ActorMethod<[], Array<Distributor>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getAllPurchaseReturns' : ActorMethod<[], Array<PurchaseReturn>>,
  'getAllPurchases' : ActorMethod<[], Array<Purchase>>,
  'getAllSalesReturns' : ActorMethod<[], Array<SalesReturn>>,
  'getBill' : ActorMethod<[bigint], Bill>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDataCounts' : ActorMethod<
    [],
    {
      'salesReturns' : bigint,
      'purchases' : bigint,
      'bills' : bigint,
      'distributors' : bigint,
      'medicines' : bigint,
      'customers' : bigint,
      'purchaseReturns' : bigint,
    }
  >,
  'getDistributor' : ActorMethod<[bigint], Distributor>,
  'getMedicine' : ActorMethod<[bigint], Medicine>,
  'getPharmacyProfile' : ActorMethod<[], PharmacyProfile>,
  'getPurchase' : ActorMethod<[bigint], Purchase>,
  'getPurchaseReturn' : ActorMethod<[bigint], PurchaseReturn>,
  'getPurchasesByDistributor' : ActorMethod<[bigint], Array<Purchase>>,
  'getSalesReturn' : ActorMethod<[bigint], SalesReturn>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'reinitializeIfEmpty' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBill' : ActorMethod<[Bill], undefined>,
  'updateCustomer' : ActorMethod<[Customer], undefined>,
  'updateDistributor' : ActorMethod<[Distributor], undefined>,
  'updateMedicine' : ActorMethod<[Medicine], undefined>,
  'updatePharmacyProfile' : ActorMethod<[PharmacyProfile], undefined>,
  'updatePurchaseReturn' : ActorMethod<[PurchaseReturn], undefined>,
  'updateSalesReturn' : ActorMethod<[SalesReturn], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];