/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Distributor = IDL.Record({
  'id' : IDL.Nat,
  'drugLicenseNumber' : IDL.Text,
  'gstNumber' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Unit = IDL.Variant({
  'bottle' : IDL.Null,
  'tablet' : IDL.Null,
  'strip' : IDL.Null,
});
export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'manufacturer' : IDL.Text,
  'purchasePrice' : IDL.Nat,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'unit' : Unit,
  'gstPercent' : IDL.Nat,
  'sellingPrice' : IDL.Nat,
  'rackLocation' : IDL.Text,
  'hsnCode' : IDL.Text,
  'batchNumber' : IDL.Text,
  'genericName' : IDL.Text,
  'reorderLevel' : IDL.Nat,
  'currentStock' : IDL.Nat,
});
export const Time = IDL.Int;
export const PurchaseItem = IDL.Record({
  'mrp' : IDL.Nat,
  'qty' : IDL.Nat,
  'purchaseRate' : IDL.Nat,
  'gstPercent' : IDL.Nat,
  'freeQty' : IDL.Nat,
  'batch' : IDL.Text,
  'expiry' : IDL.Text,
  'medicineId' : IDL.Nat,
  'amount' : IDL.Nat,
  'medicineName' : IDL.Text,
});
export const Purchase = IDL.Record({
  'id' : IDL.Nat,
  'purchaseDate' : Time,
  'distributorName' : IDL.Text,
  'distributorId' : IDL.Nat,
  'totalGST' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'invoiceDate' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'items' : IDL.Vec(PurchaseItem),
  'subtotal' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMode = IDL.Variant({
  'UPI' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const BillItem = IDL.Record({
  'discountPercent' : IDL.Nat,
  'gstAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'medicineId' : IDL.Nat,
});
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'totalGST' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'billDate' : Time,
  'billNumber' : IDL.Nat,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Nat,
  'items' : IDL.Vec(BillItem),
  'totalDiscount' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const DashboardStats = IDL.Record({
  'todayBillCount' : IDL.Nat,
  'lowStockMedicinesCount' : IDL.Nat,
  'todayTotalSales' : IDL.Nat,
  'totalMedicinesInStock' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([Customer], [IDL.Nat], []),
  'addDistributor' : IDL.Func([Distributor], [IDL.Nat], []),
  'addMedicine' : IDL.Func([Medicine], [IDL.Nat], []),
  'addPurchase' : IDL.Func([Purchase], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBill' : IDL.Func([Bill], [IDL.Nat], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteDistributor' : IDL.Func([IDL.Nat], [], []),
  'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllDistributors' : IDL.Func([], [IDL.Vec(Distributor)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDistributor' : IDL.Func([IDL.Nat], [Distributor], ['query']),
  'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
  'getPurchase' : IDL.Func([IDL.Nat], [Purchase], ['query']),
  'getPurchasesByDistributor' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Purchase)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func([Customer], [], []),
  'updateDistributor' : IDL.Func([Distributor], [], []),
  'updateMedicine' : IDL.Func([Medicine], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Distributor = IDL.Record({
    'id' : IDL.Nat,
    'drugLicenseNumber' : IDL.Text,
    'gstNumber' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Unit = IDL.Variant({
    'bottle' : IDL.Null,
    'tablet' : IDL.Null,
    'strip' : IDL.Null,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'manufacturer' : IDL.Text,
    'purchasePrice' : IDL.Nat,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'unit' : Unit,
    'gstPercent' : IDL.Nat,
    'sellingPrice' : IDL.Nat,
    'rackLocation' : IDL.Text,
    'hsnCode' : IDL.Text,
    'batchNumber' : IDL.Text,
    'genericName' : IDL.Text,
    'reorderLevel' : IDL.Nat,
    'currentStock' : IDL.Nat,
  });
  const Time = IDL.Int;
  const PurchaseItem = IDL.Record({
    'mrp' : IDL.Nat,
    'qty' : IDL.Nat,
    'purchaseRate' : IDL.Nat,
    'gstPercent' : IDL.Nat,
    'freeQty' : IDL.Nat,
    'batch' : IDL.Text,
    'expiry' : IDL.Text,
    'medicineId' : IDL.Nat,
    'amount' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  const Purchase = IDL.Record({
    'id' : IDL.Nat,
    'purchaseDate' : Time,
    'distributorName' : IDL.Text,
    'distributorId' : IDL.Nat,
    'totalGST' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'invoiceDate' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'items' : IDL.Vec(PurchaseItem),
    'subtotal' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMode = IDL.Variant({
    'UPI' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const BillItem = IDL.Record({
    'discountPercent' : IDL.Nat,
    'gstAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'medicineId' : IDL.Nat,
  });
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'totalGST' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'billDate' : Time,
    'billNumber' : IDL.Nat,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Nat,
    'items' : IDL.Vec(BillItem),
    'totalDiscount' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const DashboardStats = IDL.Record({
    'todayBillCount' : IDL.Nat,
    'lowStockMedicinesCount' : IDL.Nat,
    'todayTotalSales' : IDL.Nat,
    'totalMedicinesInStock' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([Customer], [IDL.Nat], []),
    'addDistributor' : IDL.Func([Distributor], [IDL.Nat], []),
    'addMedicine' : IDL.Func([Medicine], [IDL.Nat], []),
    'addPurchase' : IDL.Func([Purchase], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBill' : IDL.Func([Bill], [IDL.Nat], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteDistributor' : IDL.Func([IDL.Nat], [], []),
    'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllDistributors' : IDL.Func([], [IDL.Vec(Distributor)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDistributor' : IDL.Func([IDL.Nat], [Distributor], ['query']),
    'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
    'getPurchase' : IDL.Func([IDL.Nat], [Purchase], ['query']),
    'getPurchasesByDistributor' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Purchase)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func([Customer], [], []),
    'updateDistributor' : IDL.Func([Distributor], [], []),
    'updateMedicine' : IDL.Func([Medicine], [], []),
  });
};

export const init = ({ IDL }) => { return []; };