/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillItem {
    cgst: bigint;
    pack: string;
    sgst: bigint;
    hsnCode: string;
    discountPercent: bigint;
    gstAmount: bigint;
    quantity: bigint;
    batch: string;
    expiry: string;
    unitPrice: bigint;
    medicineId: bigint;
    medicineName: string;
}
export interface PurchaseItem {
    mrp: bigint;
    qty: bigint;
    purchaseRate: bigint;
    pack: string;
    gstPercent: bigint;
    hsnCode: string;
    freeQty: bigint;
    batch: string;
    expiry: string;
    medicineId: bigint;
    amount: bigint;
    medicineName: string;
}
export type Time = bigint;
export interface PharmacyProfile {
    drugLicenseNumber: string;
    gstNumber: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface Distributor {
    id: bigint;
    drugLicenseNumber: string;
    gstNumber: string;
    name: string;
    contactPerson: string;
    email: string;
    address: string;
    phone: string;
}
export interface DashboardStats {
    todayBillCount: bigint;
    lowStockMedicinesCount: bigint;
    todayTotalSales: bigint;
    totalMedicinesInStock: bigint;
}
export interface SalesReturnItem {
    cgst: bigint;
    pack: string;
    sgst: bigint;
    hsnCode: string;
    gstAmount: bigint;
    quantity: bigint;
    batch: string;
    expiry: string;
    unitPrice: bigint;
    medicineId: bigint;
    amount: bigint;
    medicineName: string;
}
export interface Customer {
    id: bigint;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface SalesReturn {
    id: bigint;
    remark: string;
    customerName: string;
    doctorAddress: string;
    totalGST: bigint;
    grandTotal: bigint;
    customerAddress: string;
    customerId: bigint;
    items: Array<SalesReturnItem>;
    doctorName: string;
    returnNumber: bigint;
    returnDate: Time;
    subtotal: bigint;
}
export interface PurchaseReturn {
    id: bigint;
    remark: string;
    distributorGst: string;
    distributorDlNo: string;
    distributorName: string;
    distributorId: bigint;
    totalGST: bigint;
    grandTotal: bigint;
    distributorAddress: string;
    items: Array<PurchaseReturnItem>;
    returnNumber: bigint;
    returnDate: Time;
    subtotal: bigint;
}
export interface Bill {
    id: bigint;
    remark: string;
    customerName: string;
    doctorAddress: string;
    totalGST: bigint;
    grandTotal: bigint;
    billDate: Time;
    invoiceNumber: string;
    customerAddress: string;
    billNumber: bigint;
    paymentMode: PaymentMode;
    customerId: bigint;
    items: Array<BillItem>;
    doctorName: string;
    totalDiscount: bigint;
    subtotal: bigint;
}
export interface Medicine {
    id: bigint;
    manufacturer: string;
    purchasePrice: bigint;
    expiryDate: string;
    name: string;
    unit: Unit;
    gstPercent: bigint;
    sellingPrice: bigint;
    rackLocation: string;
    hsnCode: string;
    batchNumber: string;
    genericName: string;
    reorderLevel: bigint;
    currentStock: bigint;
}
export interface Purchase {
    id: bigint;
    purchaseDate: Time;
    distributorName: string;
    distributorId: bigint;
    totalGST: bigint;
    grandTotal: bigint;
    invoiceDate: string;
    invoiceNumber: string;
    items: Array<PurchaseItem>;
    subtotal: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface PurchaseReturnItem {
    cgst: bigint;
    pack: string;
    sgst: bigint;
    hsnCode: string;
    gstAmount: bigint;
    quantity: bigint;
    batch: string;
    expiry: string;
    unitPrice: bigint;
    medicineId: bigint;
    amount: bigint;
    medicineName: string;
}
export enum PaymentMode {
    UPI = "UPI",
    card = "card",
    cash = "cash"
}
export enum Unit {
    bottle = "bottle",
    tablet = "tablet",
    strip = "strip"
}
export interface backendInterface {
    addCustomer(cust: Customer): Promise<bigint>;
    addDistributor(dist: Distributor): Promise<bigint>;
    addMedicine(med: Medicine): Promise<bigint>;
    addPurchase(purchase: Purchase): Promise<bigint>;
    createBill(bill: Bill): Promise<bigint>;
    createPurchaseReturn(ret: PurchaseReturn): Promise<bigint>;
    createSalesReturn(ret: SalesReturn): Promise<bigint>;
    deleteBill(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteDistributor(id: bigint): Promise<void>;
    deleteMedicine(id: bigint): Promise<void>;
    deletePurchaseReturn(id: bigint): Promise<void>;
    deleteSalesReturn(id: bigint): Promise<void>;
    getAllBills(): Promise<Array<Bill>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllDistributors(): Promise<Array<Distributor>>;
    getAllMedicines(): Promise<Array<Medicine>>;
    getAllPurchaseReturns(): Promise<Array<PurchaseReturn>>;
    getAllPurchases(): Promise<Array<Purchase>>;
    getAllSalesReturns(): Promise<Array<SalesReturn>>;
    getBill(id: bigint): Promise<Bill>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCustomer(id: bigint): Promise<Customer>;
    getDashboardStats(): Promise<DashboardStats>;
    getDataCounts(): Promise<{
        salesReturns: bigint;
        purchases: bigint;
        bills: bigint;
        distributors: bigint;
        medicines: bigint;
        customers: bigint;
        purchaseReturns: bigint;
    }>;
    getDistributor(id: bigint): Promise<Distributor>;
    getMedicine(id: bigint): Promise<Medicine>;
    getPharmacyProfile(): Promise<PharmacyProfile>;
    getPurchase(id: bigint): Promise<Purchase>;
    getPurchaseReturn(id: bigint): Promise<PurchaseReturn>;
    getPurchasesByDistributor(distributorId: bigint): Promise<Array<Purchase>>;
    getSalesReturn(id: bigint): Promise<SalesReturn>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    reinitializeIfEmpty(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBill(bill: Bill): Promise<void>;
    updateCustomer(cust: Customer): Promise<void>;
    updateDistributor(dist: Distributor): Promise<void>;
    updateMedicine(med: Medicine): Promise<void>;
    updatePharmacyProfile(profile: PharmacyProfile): Promise<void>;
    updatePurchaseReturn(ret: PurchaseReturn): Promise<void>;
    updateSalesReturn(ret: SalesReturn): Promise<void>;
}
import type { Bill as _Bill, BillItem as _BillItem, Medicine as _Medicine, PaymentMode as _PaymentMode, Time as _Time, Unit as _Unit, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: Customer): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addDistributor(arg0: Distributor): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDistributor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDistributor(arg0);
            return result;
        }
    }
    async addMedicine(arg0: Medicine): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(to_candid_Medicine_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(to_candid_Medicine_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPurchase(arg0: Purchase): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPurchase(arg0);
            return result;
        }
    }
    async createBill(arg0: Bill): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(to_candid_Bill_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(to_candid_Bill_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPurchaseReturn(arg0: PurchaseReturn): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseReturn(arg0);
            return result;
        }
    }
    async createSalesReturn(arg0: SalesReturn): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSalesReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSalesReturn(arg0);
            return result;
        }
    }
    async deleteBill(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteDistributor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDistributor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDistributor(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async deletePurchaseReturn(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchaseReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchaseReturn(arg0);
            return result;
        }
    }
    async deleteSalesReturn(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalesReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalesReturn(arg0);
            return result;
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllDistributors(): Promise<Array<Distributor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDistributors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDistributors();
            return result;
        }
    }
    async getAllMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPurchaseReturns(): Promise<Array<PurchaseReturn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchaseReturns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchaseReturns();
            return result;
        }
    }
    async getAllPurchases(): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchases();
            return result;
        }
    }
    async getAllSalesReturns(): Promise<Array<SalesReturn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalesReturns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalesReturns();
            return result;
        }
    }
    async getBill(arg0: bigint): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_Bill_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_Bill_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDataCounts(): Promise<{
        salesReturns: bigint;
        purchases: bigint;
        bills: bigint;
        distributors: bigint;
        medicines: bigint;
        customers: bigint;
        purchaseReturns: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataCounts();
            return result;
        }
    }
    async getDistributor(arg0: bigint): Promise<Distributor> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistributor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistributor(arg0);
            return result;
        }
    }
    async getMedicine(arg0: bigint): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicine(arg0);
                return from_candid_Medicine_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicine(arg0);
            return from_candid_Medicine_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPharmacyProfile(): Promise<PharmacyProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacyProfile();
            return result;
        }
    }
    async getPurchase(arg0: bigint): Promise<Purchase> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchase(arg0);
            return result;
        }
    }
    async getPurchaseReturn(arg0: bigint): Promise<PurchaseReturn> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseReturn(arg0);
            return result;
        }
    }
    async getPurchasesByDistributor(arg0: bigint): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchasesByDistributor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchasesByDistributor(arg0);
            return result;
        }
    }
    async getSalesReturn(arg0: bigint): Promise<SalesReturn> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesReturn(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async reinitializeIfEmpty(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reinitializeIfEmpty();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reinitializeIfEmpty();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBill(arg0: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(to_candid_Bill_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(to_candid_Bill_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return result;
        }
    }
    async updateDistributor(arg0: Distributor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDistributor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDistributor(arg0);
            return result;
        }
    }
    async updateMedicine(arg0: Medicine): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(to_candid_Medicine_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(to_candid_Medicine_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePharmacyProfile(arg0: PharmacyProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePharmacyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePharmacyProfile(arg0);
            return result;
        }
    }
    async updatePurchaseReturn(arg0: PurchaseReturn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseReturn(arg0);
            return result;
        }
    }
    async updateSalesReturn(arg0: SalesReturn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalesReturn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalesReturn(arg0);
            return result;
        }
    }
}
function from_candid_Bill_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Medicine_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medicine): Medicine {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Unit_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Unit): Unit {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    remark: string;
    customerName: string;
    doctorAddress: string;
    totalGST: bigint;
    grandTotal: bigint;
    billDate: _Time;
    invoiceNumber: string;
    customerAddress: string;
    billNumber: bigint;
    paymentMode: _PaymentMode;
    customerId: bigint;
    items: Array<_BillItem>;
    doctorName: string;
    totalDiscount: bigint;
    subtotal: bigint;
}): {
    id: bigint;
    remark: string;
    customerName: string;
    doctorAddress: string;
    totalGST: bigint;
    grandTotal: bigint;
    billDate: Time;
    invoiceNumber: string;
    customerAddress: string;
    billNumber: bigint;
    paymentMode: PaymentMode;
    customerId: bigint;
    items: Array<BillItem>;
    doctorName: string;
    totalDiscount: bigint;
    subtotal: bigint;
} {
    return {
        id: value.id,
        remark: value.remark,
        customerName: value.customerName,
        doctorAddress: value.doctorAddress,
        totalGST: value.totalGST,
        grandTotal: value.grandTotal,
        billDate: value.billDate,
        invoiceNumber: value.invoiceNumber,
        customerAddress: value.customerAddress,
        billNumber: value.billNumber,
        paymentMode: from_candid_PaymentMode_n12(_uploadFile, _downloadFile, value.paymentMode),
        customerId: value.customerId,
        items: value.items,
        doctorName: value.doctorName,
        totalDiscount: value.totalDiscount,
        subtotal: value.subtotal
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    manufacturer: string;
    purchasePrice: bigint;
    expiryDate: string;
    name: string;
    unit: _Unit;
    gstPercent: bigint;
    sellingPrice: bigint;
    rackLocation: string;
    hsnCode: string;
    batchNumber: string;
    genericName: string;
    reorderLevel: bigint;
    currentStock: bigint;
}): {
    id: bigint;
    manufacturer: string;
    purchasePrice: bigint;
    expiryDate: string;
    name: string;
    unit: Unit;
    gstPercent: bigint;
    sellingPrice: bigint;
    rackLocation: string;
    hsnCode: string;
    batchNumber: string;
    genericName: string;
    reorderLevel: bigint;
    currentStock: bigint;
} {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        purchasePrice: value.purchasePrice,
        expiryDate: value.expiryDate,
        name: value.name,
        unit: from_candid_Unit_n17(_uploadFile, _downloadFile, value.unit),
        gstPercent: value.gstPercent,
        sellingPrice: value.sellingPrice,
        rackLocation: value.rackLocation,
        hsnCode: value.hsnCode,
        batchNumber: value.batchNumber,
        genericName: value.genericName,
        reorderLevel: value.reorderLevel,
        currentStock: value.currentStock
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    card: null;
} | {
    cash: null;
}): PaymentMode {
    return "UPI" in value ? PaymentMode.UPI : "card" in value ? PaymentMode.card : "cash" in value ? PaymentMode.cash : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bottle: null;
} | {
    tablet: null;
} | {
    strip: null;
}): Unit {
    return "bottle" in value ? Unit.bottle : "tablet" in value ? Unit.tablet : "strip" in value ? Unit.strip : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medicine>): Array<Medicine> {
    return value.map((x)=>from_candid_Medicine_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Bill_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bill): _Bill {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Medicine_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Medicine): _Medicine {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Unit_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unit): _Unit {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    manufacturer: string;
    purchasePrice: bigint;
    expiryDate: string;
    name: string;
    unit: Unit;
    gstPercent: bigint;
    sellingPrice: bigint;
    rackLocation: string;
    hsnCode: string;
    batchNumber: string;
    genericName: string;
    reorderLevel: bigint;
    currentStock: bigint;
}): {
    id: bigint;
    manufacturer: string;
    purchasePrice: bigint;
    expiryDate: string;
    name: string;
    unit: _Unit;
    gstPercent: bigint;
    sellingPrice: bigint;
    rackLocation: string;
    hsnCode: string;
    batchNumber: string;
    genericName: string;
    reorderLevel: bigint;
    currentStock: bigint;
} {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        purchasePrice: value.purchasePrice,
        expiryDate: value.expiryDate,
        name: value.name,
        unit: to_candid_Unit_n3(_uploadFile, _downloadFile, value.unit),
        gstPercent: value.gstPercent,
        sellingPrice: value.sellingPrice,
        rackLocation: value.rackLocation,
        hsnCode: value.hsnCode,
        batchNumber: value.batchNumber,
        genericName: value.genericName,
        reorderLevel: value.reorderLevel,
        currentStock: value.currentStock
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    remark: string;
    customerName: string;
    doctorAddress: string;
    totalGST: bigint;
    grandTotal: bigint;
    billDate: Time;
    invoiceNumber: string;
    customerAddress: string;
    billNumber: bigint;
    paymentMode: PaymentMode;
    customerId: bigint;
    items: Array<BillItem>;
    doctorName: string;
    totalDiscount: bigint;
    subtotal: bigint;
}): {
    id: bigint;
    remark: string;
    customerName: string;
    doctorAddress: string;
    totalGST: bigint;
    grandTotal: bigint;
    billDate: _Time;
    invoiceNumber: string;
    customerAddress: string;
    billNumber: bigint;
    paymentMode: _PaymentMode;
    customerId: bigint;
    items: Array<_BillItem>;
    doctorName: string;
    totalDiscount: bigint;
    subtotal: bigint;
} {
    return {
        id: value.id,
        remark: value.remark,
        customerName: value.customerName,
        doctorAddress: value.doctorAddress,
        totalGST: value.totalGST,
        grandTotal: value.grandTotal,
        billDate: value.billDate,
        invoiceNumber: value.invoiceNumber,
        customerAddress: value.customerAddress,
        billNumber: value.billNumber,
        paymentMode: to_candid_PaymentMode_n7(_uploadFile, _downloadFile, value.paymentMode),
        customerId: value.customerId,
        items: value.items,
        doctorName: value.doctorName,
        totalDiscount: value.totalDiscount,
        subtotal: value.subtotal
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unit): {
    bottle: null;
} | {
    tablet: null;
} | {
    strip: null;
} {
    return value == Unit.bottle ? {
        bottle: null
    } : value == Unit.tablet ? {
        tablet: null
    } : value == Unit.strip ? {
        strip: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    UPI: null;
} | {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMode.UPI ? {
        UPI: null
    } : value == PaymentMode.card ? {
        card: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
